#ifndef DEFINES_H_
#define DEFINES_H_

#define VIKING_DAMAGE_VS_PHOENIX VIKING_DAMAGE*2
#define BATTLE_CRUISER_YAMATO_DAMAGE BATTLE_CRUISER_DAMAGE*5
#define SHIP_TYPES 4
#define NUMBER_OF_FLEETS 2

#define SHIP_HEALTH (int[]) {BATTLE_CRUISER_HEALTH,VIKING_HEALTH,CARRIER_HEALTH,PHOENIX_HEALTH}
#define SHIP_DAMAGE (int[]) {BATTLE_CRUISER_DAMAGE,VIKING_DAMAGE,CARRIER_DAMAGE,PHOENIX_DAMAGE}
#define PROTOS_SHIP_SHIELD (int[]) {0,0,CARRIER_SHIELD,PHOENIX_SHIELD}
#define PROTOS_SHIP_REGENERATION (int[]) {0,0,CARRIER_SHIELD_REGENERATE_RATE,PHOENIX_SHIELD_REGENERATE_RATE}

#define BEGIN 0

enum AirShipDefines {
    BATTLE_CRUISER_HEALTH = 450,
    BATTLE_CRUISER_DAMAGE = 40,

    VIKING_HEALTH = 150,
    VIKING_DAMAGE = 15,

    CARRIER_HEALTH = 200,
    CARRIER_SHIELD = 150,
    CARRIER_DAMAGE = 8,
    CARRIER_SHIELD_REGENERATE_RATE = 40,

    PHOENIX_HEALTH = 90,
    PHOENIX_SHIELD = 90,
    PHOENIX_DAMAGE = 20,
    PHOENIX_SHIELD_REGENERATE_RATE = 20
};

enum AirShipType {
    BATTLE_CRUISER,
    VIKING,
    CARRIER,
    PHOENIX
};

enum CarrierDefines {
    MAX_INTERCEPTORS = 8,
    DAMAGED_STATUS_INTERCEPTORS = 4
};

enum BattleCruiserDefines {
    YAMATO_CANNON_LOADING_TURNS = 4
};
enum Fleets {
    TERRAN_FLEET = 0,
    PROTOS_FLEET = 1
};
#endif /* DEFINES_H_ */
